AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100

# Allow classes longer than 100 lines of code
ClassLength:
  Max: 250 # or whatever ends up being appropriate

Style/AccessorMethodName:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false